---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('deployment_identifier')}"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

domain_name: 'greasedscone.uk'
public_zone_id: 'Z4Q2X3ESOZT4N'
private_zone_id: 'Z2CDAFD23Q10HO'

l1_lb_port: 80
l1_lb_protocol: 'HTTP'
l1_instance_port: 80
l1_instance_protocol: 'HTTP'
l1_allow_cidr: '0.0.0.0/0'

l2_lb_port: 6567
l2_lb_protocol: 'SSL'
l2_instance_port: 6567
l2_instance_protocol: 'SSL'
l2_ssl_certificate_id: "arn:aws:iam::579878096224:server-certificate/wildcard-certificate-classic-load-balancer-test"
l2_allow_cidr: '10.0.0.0/8'

listeners:
  - lb_port: 80
    lb_protocol: "HTTP"
    instance_port: 80
    instance_protocol: "HTTP"
    ssl_certificate_id: ""
  - lb_port: 6567
    lb_protocol: "SSL"
    instance_port: 6567
    instance_protocol: "SSL"
    ssl_certificate_id: "arn:aws:iam::579878096224:server-certificate/wildcard-certificate-classic-load-balancer-test"

access_control:
  - lb_port: 80
    instance_port: 80
    allow_cidrs:
      - "0.0.0.0/0"
  - lb_port: 6567
    instance_port: 6567
    allow_cidrs:
      - "10.0.0.0/8"

egress_cidrs: []

health_check_target: 'HTTP:8080/api/ping'
health_check_timeout: 10
health_check_interval: 20
health_check_unhealthy_threshold: 5
health_check_healthy_threshold: 5

enable_cross_zone_load_balancing: 'no'

enable_connection_draining: 'yes'
connection_draining_timeout: 60

idle_timeout: 120

include_public_dns_record: 'no'
include_private_dns_record: 'yes'

expose_to_public_internet: 'no'

vpc_cidr: '10.1.0.0/16'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

dependencies:
  - "other"
  - "stuff"

service_certificate_body: "%{hiera('project_directory')}/config/secrets/certificates/cert.pem"
service_certificate_private_key: "%{hiera('project_directory')}/config/secrets/certificates/ssl.key"
